using System.Collections.Generic;

namespace IndeedSearchUrlGenerator
{
    public class SearchParameterData
    {
        public static List<string> PositionList => new List<string>
        {
            "Satış Danışmanı",
            "Satış Temsilcisi",
            "Danışman",
            "Sekreter",
            "Öğretmen",
            "Eleman",
            "Muhasebe Elemanı",
            "Müşteri Temsilcisi",
            "Müdür",
            "Genel Başvuru",
            "Garson",
            "Mağaza Müdürü",
            "Yönetici Asistanı",
            "Uzman",
            "Çağrı Merkezi Elemanı",
            "Çağrı Merkezi Müşteri Temsilcisi",
            "İngilizce Öğretmeni",
            "Ön Muhasebe Elemanı",
            "Kasiyer",
            "Mağaza Satış Danışmanı",
            "Gayrimenkul Danışmanı",
            "Aşçı",
            "Güvenlik Görevlisi",
            "Resepsiyonist",
            "Muhasebe Uzmanı",
            "Makine Mühendisi",
            "Depo Elemanı",
            "Teknisyen",
            "Satış Mühendisi",
            "Diş Hekim"
        };

        public static List<string> CityList => new List<string>
        {
            "İstanbul",
            "Ankara",
            "İzmir",
            "Adana",
            "Adıyaman",
            "Afyonkarahisar",
            "Ağrı",
            "Aksaray",
            "Amasya",
            "Antalya",
            "Ardahan",
            "Artvin",
            "Aydın",
            "Balıkesir",
            "Bartın",
            "Batman",
            "Bayburt",
            "Bilecik",
            "Bingöl",
            "Bitlis",
            "Bolu",
            "Burdur",
            "Bursa",
            "Çanakkale",
            "Çankırı",
            "Çorum",
            "Denizli",
            "Diyarbakır",
            "Düzce",
            "Edirne",
            "Elazığ",
            "Erzincan",
            "Erzurum",
            "Eskişehir",
            "Gaziantep",
            "Giresun",
            "Gümüşhane",
            "Hakkari",
            "Hatay",
            "Iğdır",
            "Isparta",
            "Kahramanmaraş",
            "Karabük",
            "Karaman",
            "Kars",
            "Kastamonu",
            "Kayseri",
            "Kırıkkale",
            "Kırklareli",
            "Kırşehir",
            "Kilis",
            "Kocaeli",
            "Konya",
            "Kütahya",
            "Malatya",
            "Manisa",
            "Mardin",
            "Mersin",
            "Muğla",
            "Muş",
            "Nevşehir",
            "Niğde",
            "Ordu",
            "Osmaniye",
            "Rize",
            "Sakarya",
            "Samsun",
            "Siirt",
            "Sinop",
            "Sivas",
            "Şırnak",
            "Tekirdağ",
            "Tokat",
            "Trabzon",
            "Tunceli",
            "Şanlıurfa",
            "Uşak",
            "Van",
            "Yalova",
            "Yozgat",
            "Zonguldak"
        };
    }
}